
version: "3.9"

services:
  database_ignite: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: mysql
    container_name: database_ignite
    restart: always
    ports: 
      - 3306:3306
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=ignite
      - MYSQL_DATABASE=rentx
      - MYSQL_ROOT_PASSWORD =ignite
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - my-db:/var/lib/mysql

   


  app:
    build: .
    container_name: rentx
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  my-db:
    driver: local